# Generated by Django 5.1.7 on 2025-03-19 10:12

import django.core.validators
import music.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_cover',
            field=models.ImageField(blank=True, null=True, upload_to='album_covers/'),
        ),
        migrations.AddField(
            model_name='artist',
            name='artist_image',
            field=models.ImageField(default='default-artist.jpg', upload_to='artists/'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='debut_year',
            field=models.IntegerField(validators=[music.models.validate_year]),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
