# Generated by Django 5.1.7 on 2025-03-17 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop', '0002_alter_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
